module.exports.FILES_PATH = '/var/www/watog_api.com/files/'
module.exports.DOCS_PATH = '/var/www/watog_api.com/docs/'
module.exports.DB_PATH = '/var/www/watog_api.com/watogDB.sqlite'
module.exports.TEST_DB_PATH = '/var/www/watog_api.com/test_watogDB.sqlite'
module.exports.ENV_PATH = '/var/www/watog_api.com/watog_env'