const User = require('./user')
const Post = require('./post')
const Category = require('./category')
const Vote = require('./vote')
const Report = require('./report')
const Verify = require('./verify')
const File = require('./file')
const Room = require('./room')
const Member = require('./member')
const Message = require('./message')

User.sync()
Post.sync()
Category.sync()
Vote.sync()
Report.sync()
Verify.sync()
File.sync()
Member.sync()
Room.sync({ force: true })
Message.sync()
